before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: ruby  
rvm:
  - "2.2.0"
services:
  - mongodb
addons:
  code_climate:
    repo_token: 5f4fbff43acb3b747d39955a26f2327b6dd161a37aad8a652089480ba3f72556
script:
  - cd dummy
  - bundle install
  - ln -s ../.git .git
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake db:test:prepare
  - CODECLIMATE_REPO_TOKEN=5f4fbff43acb3b747d39955a26f2327b6dd161a37aad8a652089480ba3f72556 bundle exec rspec
  - CODECLIMATE_REPO_TOKEN=5f4fbff43acb3b747d39955a26f2327b6dd161a37aad8a652089480ba3f72556 bundle exec cucumber
